//// <auto-generated />
//using TinyBtUrlApi.Infrastructure.Data;
//using Microsoft.EntityFrameworkCore;
//using Microsoft.EntityFrameworkCore.Infrastructure;
//using Microsoft.EntityFrameworkCore.Metadata;
//using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

//#nullable disable

//namespace TinyBtUrlApi.Infrastructure.Data.Migrations
//{
//    [DbContext(typeof(AppDbContext))]
//    partial class AppDbContextModelSnapshot : ModelSnapshot
//    {
//        protected override void BuildModel(ModelBuilder modelBuilder)
//        {
//#pragma warning disable 612, 618
//            modelBuilder
//                .HasAnnotation("ProductVersion", "10.0.0")
//                .HasAnnotation("Relational:MaxIdentifierLength", 128);

//            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

//            modelBuilder.Entity("TinyBtUrlApi.Core.ContributorAggregate.Contributor", b =>
//                {
//                    b.Property<int>("Id")
//                        .HasColumnType("int");

//                    b.Property<string>("Name")
//                        .IsRequired()
//                        .HasMaxLength(100)
//                        .HasColumnType("nvarchar(100)");

//                    b.Property<int>("Status")
//                        .HasColumnType("int");

//                    b.HasKey("Id");

//                    b.ToTable("Contributors");
//                });

//            modelBuilder.Entity("TinyBtUrlApi.Core.ContributorAggregate.Contributor", b =>
//                {
//                    b.OwnsOne("TinyBtUrlApi.Core.ContributorAggregate.PhoneNumber", "PhoneNumber", b1 =>
//                        {
//                            b1.Property<int>("ContributorId")
//                                .HasColumnType("int");

//                            b1.Property<string>("CountryCode")
//                                .IsRequired()
//                                .HasColumnType("nvarchar(max)");

//                            b1.Property<string>("Extension")
//                                .HasColumnType("nvarchar(max)");

//                            b1.Property<string>("Number")
//                                .IsRequired()
//                                .HasColumnType("nvarchar(max)");

//                            b1.HasKey("ContributorId");

//                            b1.ToTable("Contributors");

//                            b1.WithOwner()
//                                .HasForeignKey("ContributorId");
//                        });

//                    b.Navigation("PhoneNumber");
//                });
//#pragma warning restore 612, 618
//        }
//    }
//}
// <auto-generated />

// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TinyBtUrlApi.Infrastructure.Data;

#nullable disable

namespace TinyBtUrlApi.Infrastructure.Data.Migrations
{
  [DbContext(typeof(AppDbContext))]
  partial class AppDbContextModelSnapshot : ModelSnapshot
  {
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
      modelBuilder
          .HasAnnotation("ProductVersion", "10.0.3")
          .HasAnnotation("Relational:MaxIdentifierLength", 128);

      SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

      // ================= CONTRIBUTOR (existing clean architecture) =================
      modelBuilder.Entity("TinyBtUrlApi.Core.ContributorAggregate.Contributor", b =>
      {
        b.Property<int>("Id").HasColumnType("int");

        b.Property<string>("Name")
            .IsRequired()
            .HasMaxLength(100)
            .HasColumnType("nvarchar(100)");

        b.Property<int>("Status").HasColumnType("int");

        b.HasKey("Id");

        b.ToTable("Contributors");
      });

      modelBuilder.Entity("TinyBtUrlApi.Core.ContributorAggregate.Contributor", b =>
      {
        b.OwnsOne("TinyBtUrlApi.Core.ContributorAggregate.PhoneNumber", "PhoneNumber", b1 =>
        {
          b1.Property<int>("ContributorId").HasColumnType("int");

          b1.Property<string>("CountryCode")
              .IsRequired()
              .HasColumnType("nvarchar(max)");

          b1.Property<string>("Extension")
              .HasColumnType("nvarchar(max)");

          b1.Property<string>("Number")
              .IsRequired()
              .HasColumnType("nvarchar(max)");

          b1.HasKey("ContributorId");

          b1.ToTable("Contributors");

          b1.WithOwner().HasForeignKey("ContributorId");
        });

        b.Navigation("PhoneNumber");
      });

      // ================= TAG =================
      modelBuilder.Entity("TinyBtUrlApi.Core.Entities.Tag", b =>
      {
        b.Property<int>("Id")
            .ValueGeneratedOnAdd()
            .HasColumnType("int");

        SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

        b.Property<string>("Name")
            .IsRequired()
            .HasColumnType("nvarchar(max)");

        b.HasKey("Id");

        b.ToTable("Tags");
      });

      // ================= URL MAPPING =================
      modelBuilder.Entity("TinyBtUrlApi.Core.Entities.UrlMapping", b =>
      {
        b.Property<int>("Id")
            .ValueGeneratedOnAdd()
            .HasColumnType("int");

        SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

        b.Property<int>("ClickCount").HasColumnType("int");

        b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");

        b.Property<DateTime?>("DeletedAt").HasColumnType("datetime2");

        b.Property<DateTime?>("ExpirationDate").HasColumnType("datetime2");

        b.Property<bool>("IsDeleted").HasColumnType("bit");

        b.Property<string>("LongUrl")
            .IsRequired()
            .HasColumnType("nvarchar(max)");

        b.Property<string>("ShortCode")
            .IsRequired()
            .HasColumnType("nvarchar(450)");

        b.HasKey("Id");

        b.HasIndex("ShortCode").IsUnique();

        b.ToTable("UrlMappings");
      });

      // ================= URL TAG =================
      modelBuilder.Entity("TinyBtUrlApi.Core.Entities.UrlTag", b =>
      {
        b.Property<int>("UrlMappingId").HasColumnType("int");
        b.Property<int>("TagId").HasColumnType("int");

        b.HasKey("UrlMappingId", "TagId");

        b.HasIndex("TagId");

        b.ToTable("UrlTags");
      });

      modelBuilder.Entity("TinyBtUrlApi.Core.Entities.UrlTag", b =>
      {
        b.HasOne("TinyBtUrlApi.Core.Entities.Tag", "Tag")
            .WithMany("UrlTags")
            .HasForeignKey("TagId")
            .OnDelete(DeleteBehavior.Cascade)
            .IsRequired();

        b.HasOne("TinyBtUrlApi.Core.Entities.UrlMapping", "UrlMapping")
            .WithMany("UrlTags")
            .HasForeignKey("UrlMappingId")
            .OnDelete(DeleteBehavior.Cascade)
            .IsRequired();

        b.Navigation("Tag");
        b.Navigation("UrlMapping");
      });

      modelBuilder.Entity("TinyBtUrlApi.Core.Entities.Tag", b =>
      {
        b.Navigation("UrlTags");
      });

      modelBuilder.Entity("TinyBtUrlApi.Core.Entities.UrlMapping", b =>
      {
        b.Navigation("UrlTags");
      });

#pragma warning restore 612, 618
    }
  }
}
