<Project Sdk="Microsoft.NET.Sdk.Web">
  <Sdk Name="Microsoft.Build.CentralPackageVersions" Version="2.1.3" />

  <PropertyGroup>
    <PreserveCompilationContext>true</PreserveCompilationContext>
    <OutputType>Exe</OutputType>
    <WebProjectMode>true</WebProjectMode>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
    <NoWarn>
      NU1902;
      NU1903;
      NU1904;
      CS1591;
      NETSDK1206
    </NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Admin\Update\NewFolder\**" />
    <Content Remove="Admin\Update\NewFolder\**" />
    <EmbeddedResource Remove="Admin\Update\NewFolder\**" />
    <None Remove="Admin\Update\NewFolder\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Ardalis.ListStartupServices" />
    <PackageReference Include="Ardalis.Result" />
    <PackageReference Include="Ardalis.Result.AspNetCore" />
    <PackageReference Include="FastEndpoints" />
    <PackageReference Include="FastEndpoints.Swagger" />
    <PackageReference Include="Mediator.SourceGenerator">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Scalar.AspNetCore" />
    <PackageReference Include="Serilog.AspNetCore" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TinyBtUrlApi.Core\TinyBtUrlApi.Core.csproj" />
    <ProjectReference Include="..\TinyBtUrlApi.Infrastructure\TinyBtUrlApi.Infrastructure.csproj" />
    <ProjectReference Include="..\TinyBtUrlApi.UseCases\TinyBtUrlApi.UseCases.csproj" />
    <ProjectReference Include="..\TinyBtUrlApi.ServiceDefaults\TinyBtUrlApi.ServiceDefaults.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Endpoints\Urls\NewFolder\" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Auth\Delete\" />
    <Folder Include="Auth\Update\" />
    <Folder Include="Auth\Read\" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Contributors\Create.cs" />
  </ItemGroup>

</Project>
